---
apiVersion: v1
kind: Secret
metadata:
  name: simple-trino-user-admin-secret
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: $2y$10$89xReovvDLacVzRGpjOyAOONnayOgDAyIS2nW9bs5DJT98q17Dy5i

---
apiVersion: v1
kind: Secret
metadata:
  name: simple-trino-user-alice-secret
type: kubernetes.io/basic-auth
stringData:
  username: alice
  password: $2y$10$HcCa4k9v2DRrD/g7e5vEz.Bk.1xg00YTEHOZjPX7oK3KqMSt2xT8W

---
apiVersion: v1
kind: Secret
metadata:
  name: simple-trino-user-bob-secret
type: kubernetes.io/basic-auth
stringData:
  username: bob
  password: $2y$10$xVRXtYZnYuQu66SmruijPO8WHFM/UK5QPHTr.Nzf4JMcZSqt3W.2.
