apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: "0.0.362"
  nodeEnvironment: production
  hive:
    namespace: default
    name: simple-derby
  opa:
    namespace: default
    name: simple-opa
  tls:
    namespace: default
    name: trino-key-config
    storeType: JKS
  authorization:
    package: trino
    permissions:
      admin:
        schemas:
          read: true
          write: true
        tables:
          iris_parquet:
            read: true
            write: true
          iris_csv:
            read: true
      bob:
        schemas:
          read: false
          write: false
        tables:
          iris_parquet:
            read: true
  s3:
    endPoint: changeme
    accessKey: changeme
    secretKey: changeme
    sslEnabled: false
    pathStyleAccess: true
  coordinators:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          coordinator: true
          nodeDataDir: /stackable/trino/data
          passwordFileContent: |
            alice:$2y$10$HcCa4k9v2DRrD/g7e5vEz.Bk.1xg00YTEHOZjPX7oK3KqMSt2xT8W
            bob:$2y$10$xVRXtYZnYuQu66SmruijPO8WHFM/UK5QPHTr.Nzf4JMcZSqt3W.2.
            admin:$2y$10$89xReovvDLacVzRGpjOyAOONnayOgDAyIS2nW9bs5DJT98q17Dy5i
  workers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          nodeDataDir: /stackable/trino/data
