---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  image:
    productVersion: "414"
    stackableVersion: "0.0.0-dev"
  clusterConfig:
    catalogLabelSelector: {}
  coordinators:
    podOverrides: # on role level
      spec:
        tolerations:
          - key: "key1"
            operator: "Equal"
            value: "value1"
            effect: "NoSchedule"
    roleGroups:
      default:
        podOverrides: # on rolegroup level, takes precedence over the ones specified at role level
          metadata:
            labels:
              my-custom-label: super-important-label
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
