---
apiVersion: v2
name: trino-operator
version: 0.3.1
appVersion: "0.3.1"
description: The Stackable Operator for Trino
home: https://github.com/stackabletech/trino-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
